# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Refresh README.md

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run main.py
      run: |
        python nike_sync.py ${{ secrets.NIKE_REFRESH_TOKEN }}
        python main.py ${{ vars.DUOLINGO_USERNAME }} ${{ secrets.DUOLINGO_JWT }}
        
    - name: Commit and Push
      run: |
        git config user.name "yutaroishiwata"
        git config user.email "yutaro.ishiwata@gmail.com"
        if ! git diff --exit-code --quiet
        then
          git add .
          git commit -m "refresh README.md"
          git config pull.rebase false
          git push origin main
        fi
