# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Refresh data

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip t
        pip install -r requirements.txt
        
    - name: Run main.py
      run: |
        python main.py
        
    - name: Commit and Push
      run: |
          git config user.name "yutaroishiwata"
          git config user.email "yutaro.ishiwata@gmail.com"
          git add .
          git commit -m "refresh data"
          git pull
          git push origin main
